### ISSUE TITLE
Exception for the first time to use

### ISSUE THREAD

**Issue by lawrenceyang** [sbesada/MathParserLibrary#2]
Exception has occurred: SyntaxError
EOL while scanning string literal (__init__.py, line 1)
  File "C:\Users\lyang\Documents\MyCode\Python\graphql-test.py", line 1, in <module>
    from pymep.realParser import parse

**Comment by sbesada** [comment]
Hi

The bug is fixed en github but I have to upload a new versión to
https://pypi.org/.  I need a couple of days,

Regards.

**Comment by sbesada** [comment]
the bug is fixed!! Upgrade to version 1.0.2

**Comment by lawrenceyang** [comment]
Traceback (most recent call last):  File "./docker_app.py", line 3, in <module>    from pymep.realParser import parse
  File "/usr/local/lib/python3.7/site-packages/pymep/realParser.py", line 1, in <module>
    from exception import CalculatorException
ModuleNotFoundError: No module named 'exception'

**Comment by sbesada** [comment]
Hi,

I need more information about how you are using the library because I don't
get reproduce the bug. I'm testing the library using 2.7 and 3.6 python
version
Did you install the library (pypi install pymep) or did you download the
library and after that you are using the library?

Please use the last versión!!.

Kind regards
